### ISSUE TITLE
wine-d3d9-1.7.43.tar.gz VERIFY FAILED

### ISSUE THREAD

**Issue by perfect7gentleman** [NP-Hardass/wine-a-holics#3]
2015-05-24 12:24:23 (161 KB/s) - ‘/usr/portage/distfiles/wine-d3d9-1.7.43.tar.gz’ saved [33166]

!!! Fetched file: wine-d3d9-1.7.43.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      33166
!!! Expected: 33164
Refetching... File renamed to '/usr/portage/distfiles/wine-d3d9-1.7.43.tar.gz._checksum_failure_.4fvcl_d7'

**Comment by NP-Hardass** [comment]
Sorry about that!  Mind confirming that the latest commit fixes it?

**Comment by perfect7gentleman** [comment]
fixed.
