### ISSUE TITLE
mesa-9999.ebuild outdated depdencies

### ISSUE THREAD

**Issue by EoD** [NP-Hardass/wine-a-holics#6]
The ebuild is quite outdated, compared to https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/mesa/mesa-9999.ebuild

Just to mention a few things:
- >=python 2.7
- >=libdrm-2.4.64
- >=libvdpau-1.1
- amdgpu support
- and more stuff

**Comment by stalkerg** [comment]
I started editing, I hope the authors of the overlay is not abandoned.

**Comment by EoD** [comment]
No worries, @NP-Hardass is still around :)

**Comment by NP-Hardass** [comment]
Should be totally up to date
